In [1]:
# 숫자 다루기
# 튜플, 리스트, 배열

In [2]:
import numpy as np

# 튜플 만들기
x = (1,2,3,4,5)
print(x)
type(x)

(1, 2, 3, 4, 5)


tuple

In [3]:
x[4]

5

In [4]:
x[2] =100 # 튜플은 값의 변경이 불가능하다.
x

TypeError: 'tuple' object does not support item assignment

In [5]:
# 리스트 만들기
y = [1,2,3,4,5]
print(y)
type(y)

[1, 2, 3, 4, 5]


list

In [6]:
y[2]

3

In [7]:
y[2] = 100 # 리스트는 값으 변경이 가능하다.
y[2]

100

In [8]:
# 리스트에는 임의의 타입 데이터를 담을 수 있다
z = [1,'A', 3.14]
type(z)

list

In [9]:
# 리스트로부터 어레이(배열)를 만드는 예 
# np의 array 함수를 사용한다
data = [1,2,3,4,5,6] # 1차원 배열임
arr = np.array(data) # python list를 numpy ndarray로 바꾸는 함수를 사용
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [10]:
# 2차원 리스트로부터 2차원 배열을 만드는 예
data = [[1,2,3],[4,5,6],[7,8,9]]
print(data)
type(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [11]:
arr = np.array(data) # list를 ndarray로
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [12]:
# 배열의 각 항목의 타입을 알아보려면 dtype 속성값을 보면 된다
arr.dtype

dtype('int32')

In [13]:
# 배열의 구조를 보려면 shape 속성을 보면 된다
arr.shape

(3, 3)

In [14]:
# 초기값이 0인 배열을 만드는 법
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
# 레인지(범위)를 만드는 법
x = range(5)
print(x)
x[2] # 레인지는 배열처럼 값을 불러올 수 있다.

range(0, 5)


2

In [16]:
# 레인지 형태로 배열을 만드는 법
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [17]:
y[2]

2

In [18]:
# 데이터의 타입을 변경하려면 astype을 사용한다
# 정수로 구성된 배열을 부동소수 타입을 변환하는 예
z = y.astype(np.float64)
z

array([ 0.,  1.,  2.,  3.,  4.])

In [19]:
# 벡터화: 배열에 상수를 곱하거나 더할 수 있다
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
arr + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [21]:
# 배열을 곱하면 각 항목별로 곱셈을 한다
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## 실습예제 1
arr 배열에 3을 곱한 뒤 음수로 바꾸어보시오.

In [22]:
# 리스트
x = [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [23]:
# 배열
y = np.array(x)
y

array([1, 2, 3, 4, 5])

In [24]:
x[2] = 100
y[2] = 100
x

[1, 2, 100, 4, 5]

In [25]:
y

array([  1,   2, 100,   4,   5])

In [26]:
x_slice = x[3:5]
x_slice

[4, 5]

In [27]:
y_slice = y[3:5]
y_slice

array([4, 5])

In [28]:
x_slice[1] = 200
y_slice[1] = 200

In [29]:
x_slice

[4, 200]

In [30]:
y_slice

array([  4, 200])

In [31]:
# 리스트의 일부인 슬라이스 리스트에서 값을 바꾸어도 원본 리스트의 값은 달라지지 않는다
x

[1, 2, 100, 4, 5]

In [32]:
# 그러나 배열에서는 슬라이스 배열의 값을 바꾸면 원본 배열의 값도 달라진다
# list는 새로운 주소값을 생성하여 참조하지만, 배열은 동일 주소값을 참조하기 때문이다.
# 리스트와 배열의 다른 점 중 하나
y

array([  1,   2, 100,   4, 200])

### 실습예제 2
1부터 10까지의 정수를 원소로 가진 배열을 만들고, 4번째부터 6번째 까지의 값을 slice하여 출력해 보시오.

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr[1,2]

6

In [35]:
arr[1][2]

6

In [36]:
# 2차원 배열 중에 한 차원의 배열만 얻으려면 인자를 한 차원 낮게 주면 된다
# 아래는 2차원 배열 중 첫번째 행만 얻는다
arr[0]

array([1, 2, 3])

In [37]:
# 행은 1~2의 범위를 , 열은 1~3의 범위를 얻는 예이다
arr[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# 전체는 ':'로 표시할 수 있다
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# 배열의 불리언 색인
name = np.array(['kim', 'lee', 'park', 'kim'])

# 0~11 값을 얻고 이를 4x3 배열로 재구성한다
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
name == 'kim'
# 첫번째, 네번째 항목만 True를 얻는다

array([ True, False, False,  True], dtype=bool)

In [41]:
# 배열 data에서 첫번째, 네번째 행만 얻는 방법
data[name == 'kim']

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [42]:
# 배열 data에서 'kim' 또는 'lee'의 위치의 행만 얻는 방법
data[(name == 'kim') | (name == 'lee')]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11]])

In [43]:
# 5 보다 큰 값을 모두 5로 교체하는 방법
data[data > 5] = 5
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

### 실습예제 3
0부터 15까지의 정수를 가진 4*4 배열을 만들고, 7 이하의 정수를 모두 음수로 바꾸어보시오.

In [44]:
# 이름이 'kim'에 해당하는 내용을 모두 100으로 바꾸는 예
data[name =='kim'] = 100
data

array([[100, 100, 100],
       [  3,   4,   5],
       [  5,   5,   5],
       [100, 100, 100]])

In [45]:
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
# 팬시 색인 - 어레이에서 특정 행을 바로 액세스할 수 있다
# 아래는 두번째와 세번째 행을 얻는 경우이다
data[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [47]:
data[[0]]

array([[0, 1, 2]])

In [48]:
# 행의 순서를 임의의 순으로 바꿀 수 있다
# 팬시 색인으로 배열을 바꾸면 본사본이 생기며 원래의 내용을 바지 않는다
data[[3,2,0,1]]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [49]:
data
# data 내용은 그대로 남아 있다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
# 행과 열을 모두 바꾸려면 아래와 같이 한다
data[[3,2,1,0]][:,[2,1,0]]

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [51]:
# 트랜스포즌 행과 열의 위치를 바꾸는 것이다
data.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [52]:
# 배열의 곱셈은 np.dot()을 사용한다
np.dot(data,data.T)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [53]:
# 조건에 따라 값을 다르게 선택하는 예
# np.where 를 사용한다
# 아래는 5보다 크면 6으로 바꾸고 5보다 작으면 모두 3으로 바꾼다
np.where(data>5, 6, 3)

array([[3, 3, 3],
       [3, 3, 3],
       [6, 6, 6],
       [6, 6, 6]])

In [54]:
# 5보다 크면 그대로 두고 작으면 5로 바꾸는 예
np.where(data>5, data, 5)

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
# 전체의 평균을 구한다
data.mean()

5.5

In [56]:
np.mean(data)

5.5

In [57]:
data.sum()

66

In [58]:
# 각 행에 대해서 평균을 구한다 axis=1이면 행을 지칭한다
data.mean(axis=1)

array([  1.,   4.,   7.,  10.])

In [59]:
# axis를 생략해도 된다
data.mean(1)

array([  1.,   4.,   7.,  10.])

In [60]:
# 각 열에 대해서 평균을 구한다 axis=0이면 열을 지칭한다
data.mean(0)

array([ 4.5,  5.5,  6.5])

In [61]:
# 불리언 연산, True는 1로 False는 0으로 숫자로 치환하여 계산가능하다
1 + True

2

In [62]:
# 배열에서 값이 특정 수보다 큰 원소의 갯수를 반환한다.
x = np.array([1,2,3,4,5,6])
(x>4).sum()

2

In [63]:
(data>1).sum()

10

In [64]:
(x>4)

array([False, False, False, False,  True,  True], dtype=bool)

In [65]:
# True가 하나 이상 있는가?
(x==True).any()

True

In [66]:
# 모두 True인가?
(x==True).all()

False

### 실습예제 4
-5 부터 4 까지의 정수를 원소로 가진 배열을 만들고, True인 원소의 갯수를 출력해보시오.

In [67]:
# 소팅
# 리스트
y = [2,4,1,5,8,6,7,3,9]
y

[2, 4, 1, 5, 8, 6, 7, 3, 9]

In [68]:
sorted(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [69]:
# y의 내용은 바뀌지 않았다
y

[2, 4, 1, 5, 8, 6, 7, 3, 9]

In [70]:
y.sort()
y
# y의 내용이 바뀌었다

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [71]:
# 배열
z = np.array([2,4,1,5,8,6,7,3,9])
type(z)

numpy.ndarray

In [72]:
z

array([2, 4, 1, 5, 8, 6, 7, 3, 9])

In [73]:
sorted(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [74]:
z

array([2, 4, 1, 5, 8, 6, 7, 3, 9])

In [75]:
z.sort()

In [76]:
t = np.array([[8,4,11,5],[2,10,7,3],[9,12,1,6]])
t

array([[ 8,  4, 11,  5],
       [ 2, 10,  7,  3],
       [ 9, 12,  1,  6]])

In [77]:
# 열을 기준으로 소팅
t.sort(0)

In [78]:
t

array([[ 2,  4,  1,  3],
       [ 8, 10,  7,  5],
       [ 9, 12, 11,  6]])

In [79]:
# 행에서 소팅
t.sort(1)

In [80]:
t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [81]:
# 집합 set
# 리스트나 배열에서 중복된 항목을 제외하고 유일하게 있는 항목만 얻는다
# 리스트
name = ['kim', 'lee', 'park', 'kim', 'lee']

In [82]:
set(name)

{'kim', 'lee', 'park'}

In [83]:
name
# name은 바뀌지 않았다

['kim', 'lee', 'park', 'kim', 'lee']

In [84]:
type(name)

list

In [85]:
name_2 = np.unique(name)
# 배열을 리턴한다

In [86]:
name

['kim', 'lee', 'park', 'kim', 'lee']

In [87]:
name_2

array(['kim', 'lee', 'park'], 
      dtype='<U4')

In [88]:
long_name = ['kim', 'kang', 'lee', 'park', 'kim', 'lee', 'min']

In [89]:
np.in1d(long_name, ['kim'])
# 'kim'이 들어 있는 위치를 찾는다

array([ True, False, False, False,  True, False, False], dtype=bool)

In [90]:
np.in1d(long_name, name)
# 'kim', 'lee', 'park' 중 하나가 들어 있는 위치를 찾는다

array([ True, False,  True,  True,  True,  True, False], dtype=bool)

In [91]:
b = np.in1d(long_name, name)
b

array([ True, False,  True,  True,  True,  True, False], dtype=bool)

In [92]:
b.sum()

5

In [93]:
np.in1d(long_name, name).sum()

5

In [94]:
p=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# 순서를 임의로 바꾸는 방법
q = np.random.permutation(p)
q

array([4, 2, 9, 5, 7, 3, 1, 8, 6])

In [96]:
q.sort()

In [97]:
q

array([1, 2, 3, 4, 5, 6, 7, 8, 9])