## 실습예제 1
arr 배열에 3을 곱한 뒤 음수로 바꾸어보시오.

In [24]:
arr*(-3)

array([[ -3,  -6,  -9],
       [-12, -15, -18],
       [-21, -24, -27]])

### 실습예제 2
1부터 10까지의 정수를 원소로 가진 배열을 만들고, 4번째부터 6번째 까지의 값을 slice하여 출력해 보시오.

In [60]:
array = np.arange(1,10)
# array = np.array(range(1,10))
array[4:7]

array([5, 6, 7])

### 실습예제 3
0부터 15까지의 정수를 가진 4*4 배열을 만들고, 7 이하의 정수를 모두 음수로 바꾸어보시오.

In [63]:
array = np.arange(16).reshape(4,4)
array[array < 7] = array[array < 7]*-1
array

array([[ 0, -1, -2, -3],
       [-4, -5, -6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 실습예제 4
-5 부터 4 까지의 정수를 원소로 가진 배열을 만들고, True인 원소의 갯수를 출력해보시오.

In [94]:
array = np.arange(-5,5)
len(array[array==True])

1