In [47]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
from numpy import nan as NA ## numpy 안에서 nan을 Na으로 대체한다는 뜻입니다.

### 실습 예제 1
series1, series2라는 Series 기본구조를 만든다. series1은 index는 ㄱ,ㄷ,ㄹ,ㄴ 순으로 하며, value 값은 index에 자음이 들어가는 단어로 자유롭게 정하시오. series2 에는 series1을 index 순으로 정렬된 Series를 넣으시고 series1, series2를 각각 출력하시오.

In [48]:
#모법 답안
series1 = Series(['구인','도망','린스','나무'], index=['ㄱ','ㄷ','ㄹ','ㄴ'])
series2 = series1.sort_index()

series1

ㄱ    구인
ㄷ    도망
ㄹ    린스
ㄴ    나무
dtype: object

### 실습예제2
위 frame.sort_index(axis=? , ascending = ?) 에서 axis = (0 or 1), ascending = (False, True)를 자유롭게 넣어 보고 결과를 살펴본 뒤
frame2 = DataFrame(np.arange(9).reshape((3, 3)), index=['2', '3', '1'], columns=['3','1','2'])를 행과 열을 1,2,3 순으로 바꾼 뒤 출력해보시오.

In [49]:
# 인덱스가 아니라 값을 중심으로 정렬
obj = Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

### 실습예제3
행 'c'를 기준으로 정렬한 Dataframe을 변수 frame2에 넣어 출력하시오.

In [50]:
frame = DataFrame({'b': [4, 7, 3, 2], 'a': [4,9,2,5], 'c': [5,3,7,9]}) 
#답안
frame2 =frame.sort_values(by='c')
frame2

a  b  c
1  9  7  3
0  4  4  5
2  2  3  7
3  5  2  9

### 실습예제 4
frame에 rank를 적용해보시오.

In [51]:
frame = DataFrame({'b': [4,7,3,2], 'a': [4,9,2,5], 'c': [5,3,7,9]})
##답안
frame.rank() #열 기준으로 rank를 수행

a    b    c
0  2.0  3.0  2.0
1  4.0  4.0  1.0
2  1.0  2.0  3.0
3  3.0  1.0  4.0

### 실습예제 5
frame 합을 행을 기준으로 NaN이 있으면 이를 반영하지 않는 합을 구해보시오.

In [52]:
frame = DataFrame({'b': [4, 7, 3, 2], 'a': [4,9,2,5], 'c': [5,3,7,np.nan]})
#모법답안
frame.sum(axis=1,skipna=True)

0    13.0
1    19.0
2    12.0
3     7.0
dtype: float64

### 실습예제6
obj 에서 isin 문을 자유롭게 활용해보시오.

In [53]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
##모법 답안
obj[obj.isin(['g'])] ## isin는 is in을 뜻한다.

Series([], dtype: object)

### 실습예제7
위에서 np.random.randn(7,3)을 단독적으로 실행해보고 결과 값을 확인 해보시오.
활용 하여 np.random.randn 6 * 4 행렬을 만들고 DataFrame 형식으로 나타내보시오.


In [54]:
#모법답안
print(np.random.randn(7 , 3))
df2 = DataFrame(np.random.randn(6 , 4))
df2

[[-1.9464157  -1.63335042  0.93426064]
 [ 1.36756079 -0.21387309 -0.45324317]
 [ 0.32245573 -1.81751662 -1.48993746]
 [-1.46143513 -0.68178544 -0.97931052]
 [-0.19564247 -0.55160069  0.85437426]
 [-0.64135029 -0.92243788 -0.55244583]
 [-0.46503656 -1.02733709 -0.15225259]]


0         1         2         3
0  0.128336 -1.528617  0.590820  0.820984
1 -0.041242 -1.670044 -0.603456  1.727717
2 -1.154734 -0.864232  0.768594 -0.026390
3 -0.268956 -0.104225 -1.136881  1.120080
4 -0.702931 -1.718846  0.918040 -0.345967
5 -0.016562  1.116334  1.651031  1.605614

### 실습예제8
위 예제에서 만들었던 DataFrame에 (0,0) (1,1) (2,2) (3,3) 위치에 있는 값들을 Na 값으로 대체해보시오.

In [56]:
# 모법답안
df2.ix[0, 0] = NA
df2.ix[1, 1] = NA
df2.ix[2,2] = NA
df2.ix[3,3] = NA
df2

0         1         2         3
0       NaN -1.528617  0.590820  0.820984
1 -0.041242       NaN -0.603456  1.727717
2 -1.154734 -0.864232       NaN -0.026390
3 -0.268956 -0.104225 -1.136881       NaN
4 -0.702931 -1.718846  0.918040 -0.345967
5 -0.016562  1.116334  1.651031  1.605614

### 실습예제9
np.random.randn을 활용해 3*3 Dataframe 구조를 만든 뒤 값들을 확인하여 음수에 해당하는 값들을 0으로 대체해보시오.

In [57]:
##모법답안
dataframe = DataFrame(np.random.randn(3 , 3)) 
dataframe
##확인후 음수 해당 값들을 0으로 대체

0         1         2
0  1.894678 -0.740017  0.296595
1  1.013946  0.582237  1.529575
2  0.799530 -0.237239 -0.618004